# Generated by Django 3.0.2 on 2020-04-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserecord',
            name='date',
            field=models.DateField(),
        ),
    ]
